# Generated by Django 3.0.3 on 2020-03-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodityID', models.IntegerField(primary_key=True, serialize=False)),
                ('commodityName', models.TextField()),
                ('commodityPrice', models.IntegerField()),
                ('commodityDescriptionShort', models.TextField(null=True)),
                ('commodityDescriptionFull', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userName', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('eIdentifier', models.TextField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBascet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countOfCommodity', models.IntegerField(default=1)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Commodity')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Users')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableCommoditiesInStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countOfAvailable', models.IntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Commodity')),
            ],
        ),
    ]
