# Generated by Django 3.0.3 on 2020-03-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='buscetPrice',
            field=models.IntegerField(default=0),
        ),
    ]
