# Generated by Django 3.0.3 on 2020-02-22 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='nickname',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
        migrations.AddField(
            model_name='users',
            name='userName',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
