# Generated by Django 3.0.3 on 2020-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0002_auto_20200222_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
