# Generated by Django 3.0.3 on 2020-03-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0002_users_buscetprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='commodityImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
