# Generated by Django 3.0.3 on 2020-03-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0004_bascet_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='commodityDescription',
            field=models.TextField(null=True),
        ),
    ]
