# Generated by Django 3.0.3 on 2020-03-06 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0005_commodity_commoditydescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='commodityCount',
        ),
        migrations.CreateModel(
            name='AvailableCommodities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countInStore', models.IntegerField()),
                ('countCommoditiesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Commodity')),
            ],
        ),
        migrations.AddField(
            model_name='bascet',
            name='bascetAvailableCommodities',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='UserList.AvailableCommodities'),
            preserve_default=False,
        ),
    ]
