# Generated by Django 3.0.3 on 2020-03-10 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserList', '0006_auto_20200306_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableCommoditiesInStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countOfAvailable', models.IntegerField()),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Commodity')),
            ],
        ),
        migrations.CreateModel(
            name='UserBascet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Commodity')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserList.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='bascet',
            name='bascetAvailableCommodities',
        ),
        migrations.RemoveField(
            model_name='bascet',
            name='bascetCommodityID',
        ),
        migrations.RemoveField(
            model_name='bascet',
            name='bascetID',
        ),
        migrations.DeleteModel(
            name='AvailableCommodities',
        ),
        migrations.DeleteModel(
            name='Bascet',
        ),
    ]
